### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Mempler** [Mempler/IceSDK#29]
This Game Engine / SDK needs a logo, otherwise we can't really identify our self.
if anyone is interested in making one, please upload it into .assets/ and open a PR

### Requirements
* it MUST be in SVG format

yea, that's basically it

**Comment by mandyellow** [comment]
Hello! I made a logo for your project. Let me know if you like it so I can open a PR with the PNG and an SVG to you. 🦊

Logo primary version and negative version:

![image](https://user-images.githubusercontent.com/30158643/95278240-1e982900-0826-11eb-97cc-6a8eba6eb5b2.png)

**Comment by Mempler** [comment]
This looks awesome! I would love if you open a PR with that!
Could you also make a version with just the ice cube ? so we have a primary icon as well.
